services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      AUTH_SECRET: ${NEXTAUTH_SECRET}
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && node server.js"

  proxy:
    volumes:
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot_www:/var/www/certbot:ro
      - certbot_etc:/etc/letsencrypt:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_etc:/etc/letsencrypt
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done"
    networks:
      - appnet

volumes:
  certbot_www:
  certbot_etc:
